### ISSUE TITLE
2 errors in macOS / OF master branch because setTransformMatrix...

### ISSUE THREAD

**Issue by moebiussurfing** [nariakiiwatani/ofxKeyframeTween#1]
any change to switch to update to individual elements?
setTransformMatrix was deleted some time ago from OF...

```
ofxTweenTypeInterpolators.h
Error:(111, 8) no member named 'setTransformMatrix' in 'ofNode'
Error:(122, 8) no member named 'setTransformMatrix' in 'ofCamera'
```

**Comment by nariakiiwatani** [comment]
Though I don't have time to fix it now but you can do the same as former `setTransformMatrix`.
https://github.com/openframeworks/openFrameworks/blob/212c8bcf2bba0c1d92bc5dc37bd361cf27d151a1/libs/openFrameworks/3d/ofNode.cpp#L43-L53

Decompose the matrix and interpolate `position, orientation, scale` individually then set it to the ofNode instead of using `Matrix4x4TRS::getInterpolated`.
Hope it works!

**Comment by nariakiiwatani** [comment]
fixed!
additionally, I added new orbit interpolation method for camera.
Please check example and try it if you like.

**Comment by moebiussurfing** [comment]
thanks, now is working fine.
